### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by RDTm** [libertyh/ising-model#1]
Dear authors,

It seems to me that the demo is not working - when I run run_ising_demo.m, I get the following error:

**Undefined function or variable "X_train"**
**Error in ising_neurons_L1reg (line 125)**
**nsamples = size(X_train,2); % number of training samples**

**Error in run_ising_demo (line 50)**
**[all_J, all_logL, modelname] = ising_neurons_L1reg(datafile, model, nchunks);**

It seems the dataset read-in is not properly divided into training and test set.

**Comment by libertyh** [comment]
Thank you for catching the typo -- I have corrected it in the code, let me
know if it still does not work for you.
Best,
Liberty

**Comment by RDTm** [comment]
Hey,

the code is running now, but I also needed to:
    addpath('3rd_party_code/minFunc')

so maybe it's reasonable to add this to the demo file.

I can't check right now if it produces reasonable outputs (it really late
in my timezone), but hopefully if it runs it does. But if I don't get back
to you tomorrow, then it means everything is working fine.

Thanks a lot,

a.

On Mon, May 18, 2015 at 11:02 PM, Liberty Hamilton <notifications@github.com

> wrote:
> 
> Thank you for catching the typo -- I have corrected it in the code, let me
> know if it still does not work for you.
> Best,
> Liberty
>

**Comment by libertyh** [comment]
Great.  I added that line to the demo file as well, thank you for
suggesting.
Best wishes,
Liberty
